-- Per-student rolling memory for the FYP Assistant chatbot. Generated by the
-- ai-chatbot service's /summarize endpoint on session-end, then injected as
-- context on the student's next session so the assistant remembers recurring
-- themes, stated preferences, and open concerns across chats.

CREATE TABLE chat_memory (
    user_id      BIGINT     NOT NULL,
    summary_text TEXT,
    updated_at   DATETIME   NOT NULL,
    PRIMARY KEY (user_id),
    CONSTRAINT fk_chat_memory_user FOREIGN KEY (user_id)
        REFERENCES user_account(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
