package com.fyp.supervision.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Per-student rolling memory for the FYP Assistant chatbot. Holds a short
 * natural-language summary of the student's recurring themes / preferences
 * / open concerns across past chat sessions. Generated by the ai-chatbot
 * /summarize endpoint when a session ends, then injected as context on the
 * next session.
 */
@Entity
@Table(name = "chat_memory")
@Getter @Setter
@NoArgsConstructor @AllArgsConstructor
@Builder
public class ChatMemory {

    @Id
    @Column(name = "user_id")
    private Long userId;

    @JsonIgnore
    @OneToOne(fetch = FetchType.LAZY)
    @MapsId
    @JoinColumn(name = "user_id")
    private UserAccount user;

    @Column(name = "summary_text", columnDefinition = "TEXT")
    private String summaryText;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    @PreUpdate
    protected void touch() {
        updatedAt = LocalDateTime.now();
    }
}
